move.roll:
    path: /move/roll
    defaults: { _controller: AppBundle:Move:roll }

move.to:
    path: /move/to/{location}
    defaults: { _controller: AppBundle:Move:to }

draw.adventure:
    path: /draw/adventure
    defaults: { _controller: AppBundle:Draw:adventure }

card.accept:
    path: /card/accept/{id}
    defaults: { _controller: AppBundle:Card:accept }

encounter.attack:
    path: /encounter/attack/{id}
    defaults: { _controller: AppBundle:Encounter:attackCard }

encounter.fight:
    path: /encounter/fight/{id}
    defaults: { _controller: AppBundle:Encounter:fight }
