fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api.move.roll:
    path: /api/move/roll
    defaults: { _controller: AppBundle:Move:roll }

api.move.to:
    path: /api/move/to/{location}
    defaults: { _controller: AppBundle:Move:to }

api.draw.adventure:
    path: /api/draw/adventure
    defaults: { _controller: AppBundle:Draw:adventure }

api.encounter.adventure:
    path: /api/encounter/adventure
    defaults: { _controller: AppBundle:Encounter:adventure }

api.encounter.enemy:
    path: /api/encounter/enemy
    defaults: { _controller: AppBundle:Encounter:enemy }

api.take.follower:
    path: /api/take/{id}/follower
    defaults: { _controller: AppBundle:Take:follower }

api.take.object:
    path: /api/take/{id}/object
    defaults: { _controller: AppBundle:Take:object }

api.take.magic_object:
    path: /api/take/{id}/magic-object
    defaults: { _controller: AppBundle:Take:magicObject }

api.fight.adventure:
    path: /api/fight/adventure
    defaults: { _controller: AppBundle:Fight:adventure }

api.turn.end:
    path: /api/turn/end
    defaults: { _controller: AppBundle:Turn:end }

frontend.start:
    path: /start
    defaults: { _controller: AppBundle:Frontend:start }
