# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.logger:
        class: AppBundle\Service\LoggerService
        arguments: [@doctrine.orm.entity_manager]
    app.move:
        class: AppBundle\Service\MoveService
    security.access.required_action:
        class: AppBundle\Security\RequiredMoveListener
        arguments: [@annotations.reader, @security.token_storage, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    security.api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: [@doctrine.orm.entity_manager]
    security.api_key_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
