<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseCardRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseCardRepository extends EntityRepository
{
}
